# Atividade de Verificação Pré-Decolagem - Missão Aurora
**Ciência da Computação - FIAP**

Esse notebook contém a lógica de verificação exigida na atividade integradora de uma espaçonave fictícia. Nele possui as seguintes informações:
1. Simulação da Telemetria
2. Script em Python

Desenvolvido com colaboração da IA (Gemini).

# Simulação da Telemetria

Contém as simulações da telemetria sem e com anomalias definidas por uma faixa segura fictícia em dez cenários diferentes e com o cálculo da análise energética.

1. **Simulação da Telemetria (sem anomalias)**

In [ ]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# Quantidade de simulação
n_rows = 10

capacidade_total_kwh = 120

# Geração de dados seguros
np.random.seed(42)

timestamps = [datetime.now() + timedelta(minutes=i*5) for i in range(n_rows)]
timestamp_strs = [t.strftime("%Y-%m-%d %H:%M:%S") for t in timestamps]

temperatura_interna_c = np.round(np.random.uniform(18, 32, n_rows), 2)
temperatura_externa_c = np.round(np.random.uniform(-8, 30, n_rows), 2)
tensao_bateria_v = np.round(np.random.uniform(26, 30, n_rows), 2)
corrente_bateria_a = np.round(np.random.uniform(10, 25, n_rows), 2)
nivel_energia_percentual = np.round(np.random.uniform(80, 100, n_rows), 2)

# Valores ajustados para garantir energia_restante > 60
carga_atual_percentual = np.round(np.random.uniform(95, 100, n_rows), 2)
perdas_energeticas_percentual = np.round(np.random.uniform(5, 7, n_rows), 2)
consumo_previsto_kwh = np.round(np.random.uniform(30, 35, n_rows), 2)
potencia_kw = np.round(np.random.uniform(0.30, 0.80, n_rows), 2)
pressao_tanques_bar = np.round(np.random.uniform(90, 140, n_rows), 2)

# Cálculos
energia_disponivel_kwh = np.round(capacidade_total_kwh * (carga_atual_percentual / 100), 2)
energia_perdida_kwh = np.round(energia_disponivel_kwh * (perdas_energeticas_percentual / 100), 2)
energia_util_kwh = np.round(energia_disponivel_kwh - energia_perdida_kwh, 2)
energia_restante_kwh = np.round(energia_util_kwh - consumo_previsto_kwh, 2)
autonomia_estimada_min = np.round((energia_restante_kwh / potencia_kw) * 60, 0)

# Estados dos sistemas
integridade_estrutural = [1] * n_rows
status_modulos_criticos = ["OK"] * n_rows
status_link_telemetria = [1] * n_rows

# Decisão de lançamento
decisao_lancamento = []
for i in range(n_rows):
    cond = (
        (18 <= temperatura_interna_c[i] <= 32) and
        (-8 <= temperatura_externa_c[i] <= 30) and
        (nivel_energia_percentual[i] >= 80) and
        (26 <= tensao_bateria_v[i] <= 30) and
        (10 <= corrente_bateria_a[i] <= 25) and
        (0.30 <= potencia_kw[i] <= 0.80) and
        (90 <= pressao_tanques_bar[i] <= 140) and
        (integridade_estrutural[i] == 1) and
        (status_modulos_criticos[i] == "OK") and
        (status_link_telemetria[i] == 1) and
        (energia_restante_kwh[i] > 60)
    )
    decisao_lancamento.append("PRONTO PARA DECOLAR" if cond else "DECOLAGEM ABORTADA")

# DataFrame com colunas
df = pd.DataFrame({
    'timestamp': timestamp_strs,
    'temperatura_interna_c': temperatura_interna_c,
    'temperatura_externa_c': temperatura_externa_c,
    'tensao_bateria_v': tensao_bateria_v,
    'corrente_bateria_a': corrente_bateria_a,
    'nivel_energia_percentual': nivel_energia_percentual,
    'capacidade_total_kwh': [capacidade_total_kwh] * n_rows,
    'energia_disponivel_kwh': energia_disponivel_kwh,
    'potencia_kw': potencia_kw,
    'perdas_energeticas_percentual': perdas_energeticas_percentual,
    'consumo_previsto_kwh': consumo_previsto_kwh,
    'carga_atual_percentual': carga_atual_percentual,
    'energia_restante_kwh': energia_restante_kwh,
    'pressao_tanques_bar': pressao_tanques_bar,
    'integridade_estrutural': integridade_estrutural,
    'status_modulos_criticos': status_modulos_criticos,
    'energia_perdida_kwh': energia_perdida_kwh,
    'energia_util_kwh': energia_util_kwh,
    'status_link_telemetria': status_link_telemetria,
    'autonomia_estimada_min': autonomia_estimada_min,
    'decisao_lancamento': decisao_lancamento
})

# Salvando CSV
csv_content = df.to_csv(index=False, sep=',', decimal='.')
with open("telemetria_aurora_siger.csv", "w") as f:
    f.write(csv_content)

print(csv_content)

In [ ]:
import pandas as pd
df_telemetria = pd.read_csv('telemetria_aurora_siger.csv')
display(df_telemetria.head(10))

,timestamp,temperatura_interna_c,temperatura_externa_c,tensao_bateria_v,corrente_bateria_a,nivel_energia_percentual,capacidade_total_kwh,energia_disponivel_kwh,potencia_kw,perdas_energeticas_percentual,...,carga_atual_percentual,energia_restante_kwh,pressao_tanques_bar,integridade_estrutural,status_modulos_criticos,energia_perdida_kwh,energia_util_kwh,status_link_telemetria,autonomia_estimada_min,decisao_lancamento
0,2026-09-10 20:05:29,23.24,-7.22,28.45,19.11,82.44,120,119.82,0.73,5.78,...,99.85,79.03,95.98,1,OK,6.93,112.89,1,6496.0,PRONTO PARA DECOLAR
1,2026-09-10 20:10:29,31.31,28.86,26.56,12.56,89.90,120,118.66,0.61,5.54,...,98.88,81.10,125.66,1,OK,6.57,112.09,1,7977.0,PRONTO PARA DECOLAR
2,2026-09-10 20:15:29,28.25,23.63,27.17,10.98,80.69,120,119.64,0.47,6.66,...,99.70,81.64,128.04,1,OK,7.97,111.67,1,10422.0,PRONTO PARA DECOLAR
3,2026-09-10 20:20:29,26.38,0.07,27.47,24.23,98.19,120,119.36,0.33,5.71,...,99.47,78.46,118.06,1,OK,6.82,112.54,1,14265.0,PRONTO PARA DECOLAR
4,2026-09-10 20:25:29,20.18,-1.09,27.82,24.48,85.18,120,117.59,0.46,5.56,...,97.99,77.52,128.55,1,OK,6.54,111.05,1,10111.0,PRONTO PARA DECOLAR
5,2026-09-10 20:30:29,20.18,-1.03,29.14,22.13,93.25,120,119.53,0.46,6.09,...,99.61,78.60,114.69,1,OK,7.28,112.25,1,10252.0,PRONTO PARA DECOLAR
6,2026-09-10 20:35:29,18.81,3.56,26.80,14.57,86.23,120,114.53,0.66,5.28,...,95.44,74.62,116.14,1,OK,6.05,108.48,1,6784.0,PRONTO PARA DECOLAR
7,2026-09-10 20:40:29,30.13,11.94,28.06,11.47,90.40,120,115.18,0.62,6.60,...,95.98,77.21,111.38,1,OK,7.60,107.58,1,7472.0,PRONTO PARA DECOLAR
8,2026-09-10 20:45:29,26.42,8.41,28.37,20.26,90.93,120,114.28,0.74,5.15,...,95.23,76.60,91.27,1,OK,5.89,108.39,1,6211.0,PRONTO PARA DECOLAR
9,2026-09-10 20:50:29,27.91,3.07,26.19,16.60,83.70,120,115.96,0.54,6.97,...,96.63,77.30,95.39,1,OK,8.08,107.88,1,8589.0,PRONTO PARA DECOLAR

2. **Simulação da Telemetria (com anomalias)**

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('telemetria_aurora_siger.csv')

# Coluna de anomalia
df['anomalia_inserida'] = 'nao'

n_rows = len(df)
n_anomalies = max(1, int(n_rows * 0.03))

np.random.seed(42)
anomaly_indices = np.random.choice(df.index, n_anomalies, replace=False)
df.loc[anomaly_indices, 'anomalia_inserida'] = 'sim'

# Aplica as anomalias
for idx in anomaly_indices:
    anomaly_type = np.random.choice([
        'temp_int', 'bateria', 'pressao', 'integridade', 'modulos', 'telemetria'
    ])

    if anomaly_type == 'temp_int':
        df.loc[idx, 'temperatura_interna_c'] = np.round(np.random.uniform(50, 70), 2)
    elif anomaly_type == 'bateria':
        val = np.round(np.random.uniform(5, 25), 2)
        df.loc[idx, 'nivel_energia_percentual'] = val
        df.loc[idx, 'carga_atual_percentual'] = val # Força atualização da carga para impactar os cálculos de energia
    elif anomaly_type == 'pressao':
        if np.random.rand() > 0.5:
            df.loc[idx, 'pressao_tanques_bar'] = np.round(np.random.uniform(40, 80), 2)
        else:
            df.loc[idx, 'pressao_tanques_bar'] = np.round(np.random.uniform(160, 220), 2)
    elif anomaly_type == 'integridade':
        df.loc[idx, 'integridade_estrutural'] = 0
    elif anomaly_type == 'modulos':
        df.loc[idx, 'status_modulos_criticos'] = 'FALHA'
    elif anomaly_type == 'telemetria':
        df.loc[idx, 'status_link_telemetria'] = 0

# Recalcula a energia
df['energia_disponivel_kwh'] = np.round(df['capacidade_total_kwh'] * (df['carga_atual_percentual'] / 100), 2)
df['energia_perdida_kwh'] = np.round(df['energia_disponivel_kwh'] * (df['perdas_energeticas_percentual'] / 100), 2)
df['energia_util_kwh'] = np.round(df['energia_disponivel_kwh'] - df['energia_perdida_kwh'], 2)
df['energia_restante_kwh'] = np.round(df['energia_util_kwh'] - df['consumo_previsto_kwh'], 2)
df['autonomia_estimada_min'] = np.round((df['energia_restante_kwh'] / df['potencia_kw']) * 60, 0)

# Recalcula a decisão de lançamento
decisao = []
for i in range(len(df)):
    cond = (
        (18 <= df.loc[i, 'temperatura_interna_c'] <= 32) and
        (-8 <= df.loc[i, 'temperatura_externa_c'] <= 30) and
        (df.loc[i, 'nivel_energia_percentual'] >= 80) and
        (26 <= df.loc[i, 'tensao_bateria_v'] <= 30) and
        (10 <= df.loc[i, 'corrente_bateria_a'] <= 25) and
        (0.30 <= df.loc[i, 'potencia_kw'] <= 0.80) and
        (90 <= df.loc[i, 'pressao_tanques_bar'] <= 140) and
        (df.loc[i, 'integridade_estrutural'] == 1) and
        (df.loc[i, 'status_modulos_criticos'] == "OK") and
        (df.loc[i, 'status_link_telemetria'] == 1) and
        (df.loc[i, 'energia_restante_kwh'] > 60)
    )
    decisao.append("PRONTO PARA DECOLAR" if cond else "DECOLAGEM ABORTADA")

df['decisao_lancamento'] = decisao

# Ordena as colunas
cols = list(df.columns)
cols.remove('anomalia_inserida')
cols.insert(1, 'anomalia_inserida') # insere logo depois do timestamp
df = df[cols]

# Salva arquivo CSV
csv_path = 'telemetria_aurora_siger_anomalias.csv'
df.to_csv(csv_path, index=False, sep=',', decimal='.')

print(df.to_csv)

In [ ]:
import pandas as pd
df_telemetria = pd.read_csv('telemetria_aurora_siger_anomalias.csv')
display(df_telemetria.head(10))

,timestamp,anomalia_inserida,temperatura_interna_c,temperatura_externa_c,tensao_bateria_v,corrente_bateria_a,nivel_energia_percentual,capacidade_total_kwh,energia_disponivel_kwh,potencia_kw,...,carga_atual_percentual,energia_restante_kwh,pressao_tanques_bar,integridade_estrutural,status_modulos_criticos,energia_perdida_kwh,energia_util_kwh,status_link_telemetria,autonomia_estimada_min,decisao_lancamento
0,2026-09-10 20:05:29,nao,23.24,-7.22,28.45,19.11,82.44,120,119.82,0.73,...,99.85,79.03,95.98,1,OK,6.93,112.89,1,6496.0,PRONTO PARA DECOLAR
1,2026-09-10 20:10:29,nao,31.31,28.86,26.56,12.56,89.90,120,118.66,0.61,...,98.88,81.10,125.66,1,OK,6.57,112.09,1,7977.0,PRONTO PARA DECOLAR
2,2026-09-10 20:15:29,nao,28.25,23.63,27.17,10.98,80.69,120,119.64,0.47,...,99.70,81.64,128.04,1,OK,7.97,111.67,1,10422.0,PRONTO PARA DECOLAR
3,2026-09-10 20:20:29,nao,26.38,0.07,27.47,24.23,98.19,120,119.36,0.33,...,99.47,78.46,118.06,1,OK,6.82,112.54,1,14265.0,PRONTO PARA DECOLAR
4,2026-09-10 20:25:29,nao,20.18,-1.09,27.82,24.48,85.18,120,117.59,0.46,...,97.99,77.52,128.55,1,OK,6.54,111.05,1,10111.0,PRONTO PARA DECOLAR
5,2026-09-10 20:30:29,nao,20.18,-1.03,29.14,22.13,93.25,120,119.53,0.46,...,99.61,78.60,114.69,1,OK,7.28,112.25,1,10252.0,PRONTO PARA DECOLAR
6,2026-09-10 20:35:29,nao,18.81,3.56,26.80,14.57,86.23,120,114.53,0.66,...,95.44,74.62,116.14,1,OK,6.05,108.48,1,6784.0,PRONTO PARA DECOLAR
7,2026-09-10 20:40:29,nao,30.13,11.94,28.06,11.47,90.40,120,115.18,0.62,...,95.98,77.21,111.38,1,OK,7.60,107.58,1,7472.0,PRONTO PARA DECOLAR
8,2026-09-10 20:45:29,sim,26.42,8.41,28.37,20.26,90.93,120,114.28,0.74,...,95.23,76.60,187.55,1,OK,5.89,108.39,1,6211.0,DECOLAGEM ABORTADA
9,2026-09-10 20:50:29,nao,27.91,3.07,26.19,16.60,83.70,120,115.96,0.54,...,96.63,77.30,95.39,1,OK,8.08,107.88,1,8589.0,PRONTO PARA DECOLAR

# Script em Python
Lógica do algoritmo em Python simulando leitura dos dados, execução das verificações e o resultado final.

**Bibliotecas**

Bibliotecas responsáveis pela criação da tabela de telemetria (pandas), geração de valores aleatórios (numpy) e criação dos horários de coleta (datetime).

In [ ]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

**Telemetria**

Definido o registro de dez simulações, capacidade total da bateria  e a geração de valores dentro da faixa segura.

In [15]:
n_rows = 10

capacidade_total_kwh = 120

temperatura_interna_c = np.round(np.random.uniform(18, 32, n_rows), 2)
temperatura_externa_c = np.round(np.random.uniform(-8, 30, n_rows), 2)
nivel_energia_percentual = np.round(np.random.uniform(80, 100, n_rows), 2)
pressao_tanques_bar = np.round(np.random.uniform(90, 140, n_rows), 2)
carga_atual_percentual = np.round(np.random.uniform(95, 100, n_rows), 2)
perdas_energeticas_percentual = np.round(np.random.uniform(5, 7, n_rows), 2)
consumo_previsto_kwh = np.round(np.random.uniform(30, 35, n_rows), 2)
potencia_kw = np.round(np.random.uniform(0.30, 0.80, n_rows), 2)

**Cálculo Energético**

Calculo da energia disponível, a energia perdida, a energia útil após as perdas e o resultado mostrará a energia restante disponível para a missão.

In [13]:
energia_disponivel_kwh = capacidade_total_kwh * (carga_atual_percentual / 100)
energia_perdida_kwh = energia_disponivel_kwh * (perdas_energeticas_percentual / 100)
energia_util_kwh = energia_disponivel_kwh - energia_perdida_kwh
energia_restante_kwh = energia_util_kwh - consumo_previsto_kwh

print("Energia disponível: ", energia_disponivel_kwh)
print("Energia útil: ", energia_util_kwh)
print("Energia restante: ", energia_restante_kwh)

Energia disponível:  [115.248 117.408 114.192 119.052 116.7   116.376 119.556 118.368 115.956
 117.42 ]
Energia útil:  [108.2870208 109.2833664 106.5525552 111.3255252 109.60464   109.1956008
 111.2707692 111.0173472 109.520442  110.856222 ]
Energia restante:  [77.4570208 79.2033664 74.4325552 79.3555252 78.13464   79.1256008
 80.2807692 77.4573472 75.570442  77.826222 ]

**Execução das verificações**

Momento que o algoritmo executa a verificação dos dados referentes a telemetria como temperatura interna e externa, integridade estrutural, níveis de energia, tensão de corrente da bateria, potência, pressão do tanque, energia restante e status dos módulos críticos. Caso o algoritmo não possua anomalias irá executar "PRONTO PARA DECOLAR", se não é executado "DECOLAGEM ABORTADA".

In [12]:
def verificar_pre_decolagem(linha):

    falhas = []

    if not (18 <= linha["temperatura_interna_c"] <= 32):
        falhas.append("Temperatura interna fora da faixa segura.")

    if not (-8 <= linha["temperatura_externa_c"] <= 30):
        falhas.append("Temperatura externa fora da faixa segura.")

    if linha["nivel_energia_percentual"] < 80:
        falhas.append("Nível de energia abaixo de 80%.")

    if not (26 <= linha["tensao_bateria_v"] <= 30):
        falhas.append("Tensão da bateria fora da faixa segura.")

    if not (10 <= linha["corrente_bateria_a"] <= 25):
        falhas.append("Corrente da bateria fora da faixa segura.")

    if not (0.30 <= linha["potencia_kw"] <= 0.80):
        falhas.append("Potência fora da faixa segura.")

    if not (90 <= linha["pressao_tanques_bar"] <= 140):
        falhas.append("Pressão dos tanques fora da faixa segura.")

    if linha["integridade_estrutural"] != 1:
        falhas.append("Falha na integridade estrutural.")

    if linha["status_modulos_criticos"] != "OK":
        falhas.append("Falha em módulo crítico.")

    if linha["status_link_telemetria"] != 1:
        falhas.append("Perda do link de telemetria.")

    if linha["energia_restante_kwh"] <= 60:
        falhas.append("Energia restante insuficiente para a missão.")

    if len(falhas) == 0:
        return "PRONTO PARA DECOLAR", "Nenhuma anomalia encontrada."
    else:
        return "DECOLAGEM ABORTADA", "; ".join(falhas)

df = pd.read_csv('telemetria_aurora_siger_anomalias.csv')

print("\nIniciando análise da telemetria...\n")

for indice, linha in df.iterrows():

    status, motivo = verificar_pre_decolagem(linha)

    print("-" * 60)
    print(f"Registro da Telemetria: {indice + 1}")
    print(f"Horário: {linha['timestamp']}")

    print(f"Temperatura interna : {linha['temperatura_interna_c']} °C")
    print(f"Temperatura externa : {linha['temperatura_externa_c']} °C")
    print(f"Nível de energia    : {linha['nivel_energia_percentual']} %")
    print(f"Pressão dos tanques : {linha['pressao_tanques_bar']} bar")
    print(f"Energia restante    : {linha['energia_restante_kwh']} kWh")

    print("\nResultado da Verificação:")
    print(status)

    print("Motivo:")
    print(motivo)

print("\n" + "=" * 60)
print(" VERIFICAÇÃO OPERACIONAL FINALIZADA ")
print("=" * 60)

Iniciando análise da telemetria...

------------------------------------------------------------
Registro da Telemetria: 1
Horário: 2026-09-10 20:05:29
Temperatura interna : 23.24 °C
Temperatura externa : -7.22 °C
Nível de energia    : 82.44 %
Pressão dos tanques : 95.98 bar
Energia restante    : 79.03 kWh

Resultado da Verificação:
PRONTO PARA DECOLAR
Motivo:
Nenhuma anomalia encontrada.
------------------------------------------------------------
Registro da Telemetria: 2
Horário: 2026-09-10 20:10:29
Temperatura interna : 31.31 °C
Temperatura externa : 28.86 °C
Nível de energia    : 89.9 %
Pressão dos tanques : 125.66 bar
Energia restante    : 81.1 kWh

Resultado da Verificação:
PRONTO PARA DECOLAR
Motivo:
Nenhuma anomalia encontrada.
------------------------------------------------------------
Registro da Telemetria: 3
Horário: 2026-09-10 20:15:29
Temperatura interna : 28.25 °C
Temperatura externa : 23.63 °C
Nível de energia    : 80.69 %
Pressão dos tanques : 128.04 bar
Energia restante    : 81.64 kWh

Resultado da Verificação:
PRONTO PARA DECOLAR
Motivo:
Nenhuma anomalia encontrada.
------------------------------------------------------------
Registro da Telemetria: 4
Horário: 2026-09-10 20:20:29
Temperatura interna : 26.38 °C
Temperatura externa : 0.07 °C
Nível de energia    : 98.19 %
Pressão dos tanques : 118.06 bar
Energia restante    : 78.46 kWh

Resultado da Verificação:
PRONTO PARA DECOLAR
Motivo:
Nenhuma anomalia encontrada.
------------------------------------------------------------
Registro da Telemetria: 5
Horário: 2026-09-10 20:25:29
Temperatura interna : 20.18 °C
Temperatura externa : -1.09 °C
Nível de energia    : 85.18 %
Pressão dos tanques : 128.55 bar
Energia restante    : 77.52 kWh

Resultado da Verificação:
PRONTO PARA DECOLAR
Motivo:
Nenhuma anomalia encontrada.
------------------------------------------------------------
Registro da Telemetria: 6
Horário: 2026-09-10 20:30:29
Temperatura interna : 20.18 °C
Temperatura externa : -1.03 °C
Nível de energia    : 93.25 %
Pressão dos tanques : 114.69 bar
Energia restante    : 78.6 kWh

Resultado da Verificação:
PRONTO PARA DECOLAR
Motivo:
Nenhuma anomalia encontrada.
------------------------------------------------------------
Registro da Telemetria: 7
Horário: 2026-09-10 20:35:29
Temperatura interna : 18.81 °C
Temperatura externa : 3.56 °C
Nível de energia    : 86.23 %
Pressão dos tanques : 116.14 bar
Energia restante    : 74.62 kWh

Resultado da Verificação:
PRONTO PARA DECOLAR
Motivo:
Nenhuma anomalia encontrada.
------------------------------------------------------------
Registro da Telemetria: 8
Horário: 2026-09-10 20:40:29
Temperatura interna : 30.13 °C
Temperatura externa : 11.94 °C
Nível de energia    : 90.4 %
Pressão dos tanques : 111.38 bar
Energia restante    : 77.21 kWh

Resultado da Verificação:
PRONTO PARA DECOLAR
Motivo:
Nenhuma anomalia encontrada.
------------------------------------------------------------
Registro da Telemetria: 9
Horário: 2026-09-10 20:45:29
Temperatura interna : 26.42 °C
Temperatura externa : 8.41 °C
Nível de energia    : 90.93 %
Pressão dos tanques : 187.55 bar
Energia restante    : 76.6 kWh

Resultado da Verificação:
DECOLAGEM ABORTADA
Motivo:
Pressão dos tanques fora da faixa segura.
------------------------------------------------------------
Registro da Telemetria: 10
Horário: 2026-09-10 20:50:29
Temperatura interna : 27.91 °C
Temperatura externa : 3.07 °C
Nível de energia    : 83.7 %
Pressão dos tanques : 95.39 bar
Energia restante    : 77.3 kWh

Resultado da Verificação:
PRONTO PARA DECOLAR
Motivo:
Nenhuma anomalia encontrada.

============================================================
 VERIFICAÇÃO OPERACIONAL FINALIZADA
============================================================